CREATE TABLE [dbo].[0250_EmployeeDefinition] (
    [cr968__timesheetemployeedefinitionid] BIGINT        IDENTITY (1, 1) NOT NULL,
    [cr968_ed_approveremailid1]            VARCHAR (MAX) NULL,
    [cr968_ed_approveremailid2]            VARCHAR (MAX) NULL,
    [cr968_companyname]                    VARCHAR (MAX) NULL,
    [cr968_ed_contracttype]                VARCHAR (MAX) NULL,
    [cr968_countryofresidence]             VARCHAR (MAX) NULL,
    [cr968_dateofbirth]                    DATE          NULL,
    [cr968_dateofjoining]                  DATE          NULL,
    [cr968_dateofleaving]                  DATE          NULL,
    [cr968_department]                     VARCHAR (MAX) NULL,
    [cr968_ed_department_spanish]          VARCHAR (MAX) NULL,
    [cr968_designation]                    VARCHAR (MAX) NULL,
    [cr968_ed_designation_spanish]         VARCHAR (MAX) NULL,
    [cr968_ebsnumber]                      VARCHAR (MAX) NULL,
    [cr968_emailid]                        VARCHAR (MAX) NULL,
    [cr968_ed_employeestatus]              VARCHAR (MAX) NULL,
    [cr968_ed_employeetype]                VARCHAR (MAX) NULL,
    [cr968_firstname]                      VARCHAR (MAX) NULL,
    [cr968_fullpassportnm]                 VARCHAR (MAX) NULL,
    [cr968_gender]                         VARCHAR (MAX) NULL,
    [cr968_homeairport]                    VARCHAR (MAX) NULL,
    [cr968_lasstname]                      VARCHAR (MAX) NULL,
    [cr968_maritalstatus]                  VARCHAR (MAX) NULL,
    [cr968_mobilenumber]                   VARCHAR (MAX) NULL,
    [cr968_ed_nationalidentificationnum]   VARCHAR (MAX) NULL,
    [cr968_nationality]                    VARCHAR (MAX) NULL,
    [cr968_payrollnumber]                  VARCHAR (MAX) NULL,
    [cr968_qualification]                  VARCHAR (MAX) NULL,
    [cr968_ed_remarks]                     VARCHAR (MAX) NULL,
    [cr968_residentialaddress]             VARCHAR (MAX) NULL,
    [cr968_ed_socialsecuritynum]           VARCHAR (MAX) NULL,
    [cr968_ed_timesheetrequired]           VARCHAR (MAX) NULL,
    [CreatedOn]                            DATETIME      CONSTRAINT [DF_0250_EmployeeDefinition_CreatedOn_1] DEFAULT (getdate()) NULL,
    [UpdatedOn]                            DATETIME      CONSTRAINT [DF_0250_EmployeeDefinition_UpdatedOn_1] DEFAULT (getdate()) NULL,
    [TblRowCount]                          INT           CONSTRAINT [DF_0250_EmployeeDefinition_TblRowCount_1] DEFAULT ((1)) NULL,
    [CreatedBy]                            VARCHAR (100) NULL,
    [UpdatedBy]                            VARCHAR (100) NULL,
    [IsActive]                             CHAR (1)      CONSTRAINT [DF_0250_EmployeeDefinition_IsActive_1] DEFAULT ('Y') NULL,
    [RowVersion]                           ROWVERSION    NOT NULL,
    CONSTRAINT [PK_0250_EmployeeDefinition] PRIMARY KEY CLUSTERED ([cr968__timesheetemployeedefinitionid] ASC)
);

